apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers: 
        - name: auth
          image: rg.fr-par.scw.cloud/namespace-demo-michel/scaleway-demo-auth:latest
      imagePullSecrets:
        - name: registry-secret